config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'contact#new'
  get 'contact/create'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'sites#show'
  get '/:slug', to: 'cross_pages#show'
  resources :companies, only: [:new, :create]
  resources :contacts, only: [:new, :create]

end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  belongs_to :site
  has_and_belongs_to_many :tags
  validates :name, :address, :description, presence: true
  validate :validate_contact

  paginates_per 5
  mount_uploader :picture, PictureUploader

  # validation at least one field phone, mail or website
  def validate_contact
    errors.add(:mail, "You must fill in at least one contact field") if phone.blank? && mail.blank? && website.blank?
  end
end

app/models/company_creation.rb
class CompanyCreation < ApplicationRecord

end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  belongs_to :site
  validates :user, :email, :body, presence: true
end

app/models/contact_admin.rb
class ContactAdmin < ApplicationRecord

end

app/models/cross_page.rb
# frozen_string_literal: true

class CrossPage < ApplicationRecord
  belongs_to :site
  has_and_belongs_to_many :tags, -> { order(:order) }
  validates :slug, :title, :description, presence: true
  validates :meta_title, :meta_description, :banner, presence: true
  mount_uploader :banner, BannerUploader
end

app/models/site.rb
# frozen_string_literal: true

class Site < ApplicationRecord
  has_many :companies, dependent: :destroy
  has_many :cross_pages, dependent: :destroy
  has_many :contacts, dependent: :destroy
  validates :name, :domain_name, :meta_title, :meta_description, presence: true
  validates :banner, :title, :description, :analytics, presence: true
  mount_uploader :banner, BannerUploader
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_and_belongs_to_many :companies
  has_and_belongs_to_many :cross_pages
  validates :name, presence: true
  validates :order, presence: true, uniqueness: true
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  before_action :find_site
  def new
    @company = Company.new
    @site = find_site
  end

  def find_site
    @domain_name = request.original_url.match(/coursde.*\.com/)[0]
    # @domain_name = "coursdetheatremarseille.com"
    @site = Site.find_by(domain_name: @domain_name)
  end

  def create
    @company = Company.new(company_params)
    @site = find_site
    @company.site = @site
    params[:company][:tag_ids].each do |tag_id|
      unless tag_id == ""
        tag = Tag.find(tag_id)
        @company.tags << tag
      end
    end
    if @company.save
      redirect_to root_path, notice: "Votre cours a été bien soumis."
    else
      render action: "new", error: "Can't be saved"
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :address, :mail, :phone, :website, :description, :tags, :active, :picture)
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :find_site

  def new
    @contact = Contact.new
    @site = find_site
  end

  def find_site
    # @domain_name = "coursdetheatremarseille.com"
    @domain_name = request.original_url.match(/coursde.*com/)[0]
    @site = Site.find_by(domain_name: @domain_name)
  end

  def create
    @contact = Contact.new(contacts_params)
    @site = find_site
    @contact.site = @site
    if @contact.save
      redirect_to root_path, notice: "Votre message a été bien transmis."
    else
      render action: "new", error: "Une erreur est survenue, veuillez réessayer"
    end
  end

  private

  def contacts_params
    params.require(:contact).permit(:user, :email, :body, :read)
  end
end

app/controllers/sites_controller.rb
# frozen_string_literal: true

class SitesController < ApplicationController
  before_action :set_domain, only: [:companies_in_city, :find_city_name_in_url, :show]
  def show
    # domain name to delete before action and retrieve url to uncoment
    # @domain_name = "coursdetheatremarseille.com"
    # @domain_name = request.original_url
    @site = Site.find_by(domain_name: @domain)
    @companies = Company.where(site: @site, active: true).page params[:page]
    @cross_pages = CrossPage.where(site: @site, active: true).includes(:tags).sort_by { |cp| cp.tags.first&.order || -1 }
  end

  def find_city_name_in_url
    match = /(coursdetheatre)(\w+)/.match(@domain)
    match[2]
  end

  def find_domain_from_url
    request.original_url.match(/coursde.*com/)[0]
  end

  helper_method :find_city_name_in_url

  private

  def set_domain
    # change also in contact controller and company controller
    @domain = find_domain_from_url
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/helpers/company_creation_helper.rb
module CompanyCreationHelper
end

app/helpers/contact_admin_helper.rb
module ContactAdminHelper
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

module ContactHelper
end

app/helpers/cross_pages_helper.rb
# frozen_string_literal: true

module CrossPagesHelper
end

app/helpers/sites_helper.rb
# frozen_string_literal: true

module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= content_for?(:meta) ? yield(:meta) : yield %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400i,700&display=swap" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">


    <%= stylesheet_link_tag    'application', media: 'all' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div id="section">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible alert-position" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible alert-position" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= link_to "Contactez-nous", new_contact_path %>

    <%= link_to "Proposez vos cours", new_company_path, id: "second-course" %>

    <%# <a href="#">Politique de confidentialité</a> %>
  </div>
  <div class="footer-copyright footer-copyright-size">
    ©<%= Date.today.strftime("%Y") %> Dacotha - Tous droits réservés.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="background-white">
  <div class="navbar-imparato">
    <nav class="container-nav navbar-expand-sm navbar-light ">
        <%= link_to root_path, class: "navbar-brand" do %>
          <i class="fas fa-theater-masks logo-icon"></i>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "Proposez vos cours", new_company_path, id: "first-course" %>
            </li>
          </ul>
        </div>
    </nav>
  </div>
</div>